# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Y:\tmp\kmolab_calculator\gui\button.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 380)
        Dialog.setMinimumSize(QtCore.QSize(380, 380))
        Dialog.setMaximumSize(QtCore.QSize(380, 380))
        Dialog.setSizeGripEnabled(True)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 363, 355))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.clear_all = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.clear_all.setMinimumSize(QtCore.QSize(100, 50))
        self.clear_all.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.clear_all.setFont(font)
        self.clear_all.setObjectName("clear_all")
        self.gridLayout.addWidget(self.clear_all, 1, 4, 1, 2)
        self.partial = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.partial.setMinimumSize(QtCore.QSize(50, 50))
        self.partial.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.partial.setFont(font)
        self.partial.setObjectName("partial")
        self.gridLayout.addWidget(self.partial, 4, 5, 1, 1)
        self.three = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.three.setMinimumSize(QtCore.QSize(50, 50))
        self.three.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 4, 3, 1, 1)
        self.plus_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plus_minus.setMinimumSize(QtCore.QSize(50, 50))
        self.plus_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.plus_minus.setFont(font)
        self.plus_minus.setObjectName("plus_minus")
        self.gridLayout.addWidget(self.plus_minus, 5, 3, 1, 1)
        self.clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(140)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        self.clear.setMinimumSize(QtCore.QSize(100, 50))
        self.clear.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 1, 2, 1, 2)
        self.seven = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.seven.setMinimumSize(QtCore.QSize(50, 50))
        self.seven.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 2, 1, 1, 1)
        self.display = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.display.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.display.setFont(font)
        self.display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setObjectName("display")
        self.gridLayout.addWidget(self.display, 0, 0, 1, 6)
        self.mplus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mplus.setMinimumSize(QtCore.QSize(50, 50))
        self.mplus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.mplus.setFont(font)
        self.mplus.setObjectName("mplus")
        self.gridLayout.addWidget(self.mplus, 5, 0, 1, 1)
        self.sqrt = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sqrt.setMinimumSize(QtCore.QSize(50, 50))
        self.sqrt.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.sqrt.setFont(font)
        self.sqrt.setObjectName("sqrt")
        self.gridLayout.addWidget(self.sqrt, 2, 5, 1, 1)
        self.zero = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.zero.setMinimumSize(QtCore.QSize(50, 50))
        self.zero.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 5, 1, 1, 1)
        self.mr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mr.setMinimumSize(QtCore.QSize(50, 50))
        self.mr.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.mr.setFont(font)
        self.mr.setObjectName("mr")
        self.gridLayout.addWidget(self.mr, 3, 0, 1, 1)
        self.backspace = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.backspace.setMinimumSize(QtCore.QSize(100, 50))
        self.backspace.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.backspace.setFont(font)
        self.backspace.setObjectName("backspace")
        self.gridLayout.addWidget(self.backspace, 1, 0, 1, 2)
        self.equal = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.equal.setMinimumSize(QtCore.QSize(50, 50))
        self.equal.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.gridLayout.addWidget(self.equal, 5, 5, 1, 1)
        self.nine = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.nine.setMinimumSize(QtCore.QSize(50, 50))
        self.nine.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 2, 3, 1, 1)
        self.minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.minus.setMinimumSize(QtCore.QSize(50, 50))
        self.minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 4, 4, 1, 1)
        self.one = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.one.setMinimumSize(QtCore.QSize(50, 50))
        self.one.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 4, 1, 1, 1)
        self.eight = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.eight.setMinimumSize(QtCore.QSize(50, 50))
        self.eight.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 2, 2, 1, 1)
        self.mc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mc.setMinimumSize(QtCore.QSize(50, 50))
        self.mc.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.mc.setFont(font)
        self.mc.setObjectName("mc")
        self.gridLayout.addWidget(self.mc, 2, 0, 1, 1)
        self.four = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.four.setMinimumSize(QtCore.QSize(50, 50))
        self.four.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 3, 1, 1, 1)
        self.five = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.five.setMinimumSize(QtCore.QSize(50, 50))
        self.five.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 3, 2, 1, 1)
        self.square = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.square.setMinimumSize(QtCore.QSize(50, 50))
        self.square.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.square.setFont(font)
        self.square.setObjectName("square")
        self.gridLayout.addWidget(self.square, 3, 5, 1, 1)
        self.six = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.six.setMinimumSize(QtCore.QSize(50, 50))
        self.six.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 3, 3, 1, 1)
        self.divide = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.divide.setMinimumSize(QtCore.QSize(50, 50))
        self.divide.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.divide.setFont(font)
        self.divide.setObjectName("divide")
        self.gridLayout.addWidget(self.divide, 2, 4, 1, 1)
        self.two = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.two.setMinimumSize(QtCore.QSize(50, 50))
        self.two.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 4, 2, 1, 1)
        self.ms = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ms.setMinimumSize(QtCore.QSize(50, 50))
        self.ms.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.ms.setFont(font)
        self.ms.setObjectName("ms")
        self.gridLayout.addWidget(self.ms, 4, 0, 1, 1)
        self.plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plus.setMinimumSize(QtCore.QSize(50, 50))
        self.plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.plus.setFont(font)
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 5, 4, 1, 1)
        self.dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dot.setMinimumSize(QtCore.QSize(50, 50))
        self.dot.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.dot.setFont(font)
        self.dot.setObjectName("dot")
        self.gridLayout.addWidget(self.dot, 5, 2, 1, 1)
        self.multiply = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.multiply.setMinimumSize(QtCore.QSize(50, 50))
        self.multiply.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.multiply.setFont(font)
        self.multiply.setObjectName("multiply")
        self.gridLayout.addWidget(self.multiply, 3, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculator"))
        self.clear_all.setText(_translate("Dialog", "Clear All"))
        self.partial.setText(_translate("Dialog", "1/x"))
        self.three.setText(_translate("Dialog", "3"))
        self.plus_minus.setText(_translate("Dialog", "+-"))
        self.clear.setText(_translate("Dialog", "Clear"))
        self.seven.setText(_translate("Dialog", "7"))
        self.mplus.setText(_translate("Dialog", "M+"))
        self.sqrt.setText(_translate("Dialog", "Sqrt"))
        self.zero.setText(_translate("Dialog", "0"))
        self.mr.setText(_translate("Dialog", "MR"))
        self.backspace.setText(_translate("Dialog", "Backspace"))
        self.equal.setText(_translate("Dialog", "="))
        self.nine.setText(_translate("Dialog", "9"))
        self.minus.setText(_translate("Dialog", "-"))
        self.one.setText(_translate("Dialog", "1"))
        self.eight.setText(_translate("Dialog", "8"))
        self.mc.setText(_translate("Dialog", "MC"))
        self.four.setText(_translate("Dialog", "4"))
        self.five.setText(_translate("Dialog", "5"))
        self.square.setText(_translate("Dialog", "x^2"))
        self.six.setText(_translate("Dialog", "6"))
        self.divide.setText(_translate("Dialog", "/"))
        self.two.setText(_translate("Dialog", "2"))
        self.ms.setText(_translate("Dialog", "MS"))
        self.plus.setText(_translate("Dialog", "+"))
        self.dot.setText(_translate("Dialog", "."))
        self.multiply.setText(_translate("Dialog", "*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

